name: Build and Upload Python Package to PYPI

on:
  push:
    paths:
      - 'docs/CHANGELOG.md'  # Watch for changes to the CHANGELOG.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@latest
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Get latest version from CHANGELOG.md
      id: changelog_version
      run: |
        VERSION=$(grep -Eo "^\-\s*([0-9]+\.[0-9]+\.[0-9]+)" docs/CHANGELOG.md | head -1 | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Check if version is updated
      run: |
        CURRENT_VERSION=$(python setup.py --version)
        if [ "$CURRENT_VERSION" == "$VERSION" ]; then
          echo "Version is unchanged. Skipping deployment."
          exit 0
        else
          echo "New version detected: $VERSION"
        fi

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://pypi.org/project/py7zip
